<!-- md_share_area -->
<div class="md_share_area" id="md_share_area">
	<span class="md_share_dimd" aria-hidden="true"></span>
	<div class="md_share_box ver2" role="dialog" aria-modal="true">
        <div class="title_wrap">
            <p class="title">공유하기</p>
            <button type="button" class="md_btn_share_close" title="레이어 팝업 닫힘"><span>공유하기 닫기</span></button>
        </div>
        <div class="ico_share_box">
            <button type="button" id="share_linkedin" class="li_s" title="새창열림">
                <i><img src="https://image.samsungsds.com/module_src/images/icon/ico_share_linkedin.svg?queryString=20260714094257" alt="Linkedin" /></i>
            </button>
            <button type="button" id="share_facebook" class="li_s" title="새창열림">
                <i><img src="https://image.samsungsds.com/module_src/images/icon/ico_share_facebook.svg?queryString=20260714094257" alt="Facebook" class="df_size"/></i>
            </button>
            <button type="button" id="share_twitter" class="li_s" title="새창열림">
                <i><img src="https://image.samsungsds.com/module_src/images/icon/ico_share_twitter.svg?queryString=20260714094257" alt="X(구 Twitter)" /></i>
            </button>
            <button type="button" id="share_kakaotalk" class="li_s btn_hidden_p" title="새창열림">
                <!-- PC Hidden : class="btn_hidden_p" -->
                <i><img src="https://image.samsungsds.com/module_src/images/icon/ico_share_kakao.svg?queryString=20260714094257" alt="KakaoTalk" /></i>
            </button>
            <button type="button" id="share_instargram" class="li_s" title="새창열림">
                <i><img src="https://image.samsungsds.com/module_src/images/icon/ico_share_instagram.svg?queryString=20260714094257" alt="Instagram" class="df_size" /></i>
            </button>
            <button type="button" id="share_naver" class="li_s" title="새창열림">
                <i><img src="https://image.samsungsds.com/module_src/images/icon/ico_share_naver.svg?queryString=20260714094257" alt="네이버" /></i>
            </button>
            <button type="button" id="share_link" class="li_s" title="링크 복사">
                <i><img src="https://image.samsungsds.com/module_src/images/icon/ico_share_link.svg?queryString=20260714094257" alt="링크 복사" /></i>
            </button>
        </div>
	</div>
</div>
<!-- //md_share_area -->
